ALTER TABLE progress ADD COLUMN IF NOT EXISTS daily_streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE progress ADD COLUMN IF NOT EXISTS best_daily_streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE progress ADD COLUMN IF NOT EXISTS activity_dates TEXT[] NOT NULL DEFAULT '{}';
